-- SOGANG-AIMBA7th weekly reaction stats
create extension if not exists pgcrypto;

create table if not exists public.weekly_issue_stats (
  issue_id text primary key,
  views integer not null default 0,
  likes integer not null default 0,
  checks integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.weekly_issue_stats (issue_id)
values
  ('vol-5'),
  ('vol-4'),
  ('vol-3'),
  ('vol-2'),
  ('vol-1')
on conflict (issue_id) do nothing;

alter table public.weekly_issue_stats enable row level security;

drop policy if exists "weekly_issue_stats_select"
on public.weekly_issue_stats;

create policy "weekly_issue_stats_select"
on public.weekly_issue_stats
for select
using (true);

create or replace function public.increment_weekly_issue_stat(
  p_issue_id text,
  p_field text,
  p_delta integer default 1
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  new_value integer;
begin
  if p_issue_id not in ('vol-1', 'vol-2', 'vol-3', 'vol-4', 'vol-5') then
    raise exception 'unsupported issue_id: %', p_issue_id;
  end if;

  if p_delta <> 1 then
    raise exception 'unsupported delta: %', p_delta;
  end if;

  insert into public.weekly_issue_stats (issue_id)
  values (p_issue_id)
  on conflict (issue_id) do nothing;

  if p_field = 'views' then
    update public.weekly_issue_stats
    set views = greatest(0, views + p_delta),
        updated_at = now()
    where issue_id = p_issue_id
    returning views into new_value;
  elsif p_field = 'likes' then
    update public.weekly_issue_stats
    set likes = greatest(0, likes + p_delta),
        updated_at = now()
    where issue_id = p_issue_id
    returning likes into new_value;
  elsif p_field = 'checks' then
    update public.weekly_issue_stats
    set checks = greatest(0, checks + p_delta),
        updated_at = now()
    where issue_id = p_issue_id
    returning checks into new_value;
  else
    raise exception 'unsupported field: %', p_field;
  end if;

  return new_value;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.weekly_issue_stats to anon, authenticated;
grant execute on function public.increment_weekly_issue_stat(text, text, integer) to anon, authenticated;

-- AIMBA Pulse topic votes
create table if not exists public.pulse_votes (
  id bigint generated by default as identity primary key,
  option_id text not null,
  client_key text,
  source_path text,
  created_at timestamptz not null default now()
);

create index if not exists pulse_votes_option_id_idx
on public.pulse_votes (option_id);

create index if not exists pulse_votes_created_at_idx
on public.pulse_votes (created_at desc);

delete from public.pulse_votes a
using public.pulse_votes b
where a.id > b.id
  and a.option_id = b.option_id
  and a.client_key is not null
  and a.client_key = b.client_key;

create unique index if not exists pulse_votes_option_client_key_uidx
on public.pulse_votes (option_id, client_key)
where client_key is not null;

alter table public.pulse_votes enable row level security;

drop policy if exists "pulse_votes_insert"
on public.pulse_votes;

create policy "pulse_votes_insert"
on public.pulse_votes
for insert
with check (
  option_id in (
    'ai-agent-workflow',
    'startup-funding',
    'mba-career-shift',
    'real-estate-rwa'
  )
);

create or replace view public.pulse_vote_counts as
select
  option_id,
  count(*)::integer as votes
from public.pulse_votes
group by option_id;

grant select on public.pulse_vote_counts to anon, authenticated;
grant insert on public.pulse_votes to anon, authenticated;
grant usage, select on sequence public.pulse_votes_id_seq to anon, authenticated;

-- Reader submissions for feedback, topics, links, seminars, and project signals.
create table if not exists public.participation_submissions (
  id uuid primary key default gen_random_uuid(),
  issue_id text not null default 'vol-4',
  submission_type text not null,
  member_name text,
  sector text,
  content text not null,
  link_url text,
  moderation_status text not null default 'pending',
  source_path text,
  created_at timestamptz not null default now()
);

alter table public.participation_submissions
add column if not exists moderation_status text not null default 'pending';

create index if not exists participation_submissions_issue_id_idx
on public.participation_submissions (issue_id);

create index if not exists participation_submissions_created_at_idx
on public.participation_submissions (created_at desc);

create index if not exists participation_submissions_moderation_status_idx
on public.participation_submissions (moderation_status);

alter table public.participation_submissions enable row level security;

drop policy if exists "participation_submissions_insert"
on public.participation_submissions;

create policy "participation_submissions_insert"
on public.participation_submissions
for insert
with check (
  submission_type in ('feedback', 'topic', 'tip', 'project')
  and length(content) between 2 and 2000
  and moderation_status = 'pending'
  and (
    link_url is null
    or link_url = ''
    or link_url ~* '^https?://'
  )
);

-- Keep raw submissions private by default. Review them in Supabase, then curate into briefs/reports.
grant insert on public.participation_submissions to anon, authenticated;
